In [8]:
from sklearn.datasets import fetch_openml 
mnist = fetch_openml('mnist_784', version=1)



In [4]:

%load_ext watermark
%watermark -v -p numpy,scipy,sklearn,pandas,matplotlib

CPython 3.7.4
IPython 7.8.0

numpy 1.16.5
scipy 1.3.1
sklearn 0.21.3
pandas 0.25.1
matplotlib 3.1.1


In [9]:
import numpy as np
X, y = mnist["data"], mnist["target"]
y = y.astype(np.int)

In [10]:
X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]
shuffle_index = np.random.permutation(60000) 
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
knn_clf = KNeighborsClassifier()

In [9]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [11]:
KNN_clf = KNeighborsClassifier()

In [12]:
KNN_clf.predict([X[33]])

NotFittedError: This KNeighborsClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [13]:
from sklearn.model_selection import cross_val_score

In [1]:
from sklearn.metrics import mean_squared_error

In [ ]:
predictions = knn_clf.predict(X_train)
knn_mse = mean_squared_error(y_train, predictinos)
knn_rmse = np.sqrt(knn_mse)
knn_rmse

In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
import pickle
from sklearn.externals import joblib

In [5]:
knn_clf = joblib.load('knn_clf.pkl')

ModuleNotFoundError: No module named 'sklearn.neighbors._classification'

In [7]:
knn_clf = KNeighborsClassifier(n_neighbors=1)

In [11]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [12]:
knn_clf.predict(X_train[:300])

array([6, 9, 4, 1, 1, 8, 7, 7, 8, 0, 6, 7, 1, 0, 6, 0, 9, 8, 2, 0, 1, 9,
       1, 1, 5, 9, 8, 5, 1, 2, 9, 7, 3, 0, 8, 1, 7, 5, 5, 2, 2, 5, 7, 1,
       1, 6, 8, 1, 4, 8, 5, 5, 0, 1, 4, 9, 3, 5, 2, 4, 5, 5, 2, 7, 0, 5,
       2, 0, 1, 8, 9, 5, 0, 6, 2, 4, 0, 4, 9, 0, 1, 7, 5, 2, 9, 5, 3, 3,
       8, 5, 5, 1, 1, 3, 8, 7, 5, 4, 7, 3, 0, 9, 3, 0, 9, 0, 2, 2, 7, 0,
       3, 0, 0, 3, 0, 9, 4, 5, 9, 2, 9, 1, 2, 3, 0, 0, 2, 9, 7, 5, 0, 3,
       8, 7, 2, 3, 8, 5, 6, 2, 2, 5, 3, 5, 6, 3, 6, 3, 3, 9, 4, 7, 7, 3,
       9, 3, 4, 6, 7, 0, 0, 5, 0, 5, 8, 7, 6, 8, 4, 9, 5, 7, 2, 0, 0, 4,
       7, 6, 3, 2, 5, 7, 7, 1, 5, 4, 1, 6, 3, 2, 5, 5, 0, 9, 5, 3, 7, 9,
       8, 9, 1, 0, 4, 3, 0, 1, 7, 0, 6, 1, 1, 6, 0, 8, 2, 7, 6, 8, 8, 0,
       5, 0, 7, 6, 0, 8, 2, 9, 4, 7, 0, 5, 1, 2, 1, 8, 2, 8, 6, 7, 9, 9,
       3, 4, 1, 6, 0, 8, 8, 6, 3, 0, 9, 1, 9, 8, 7, 5, 1, 6, 4, 8, 3, 4,
       6, 1, 3, 5, 9, 0, 9, 0, 5, 2, 3, 4, 4, 7, 3, 1, 6, 7, 1, 7, 7, 4,
       4, 5, 5, 1, 8, 8, 4, 2, 5, 0, 1, 6, 8, 8])

In [13]:
y_train[:300]

array([6, 9, 4, 1, 1, 8, 7, 7, 8, 0, 6, 7, 1, 0, 6, 0, 9, 8, 2, 0, 1, 9,
       1, 1, 5, 9, 8, 5, 1, 2, 9, 7, 3, 0, 8, 1, 7, 5, 5, 2, 2, 5, 7, 1,
       1, 6, 8, 1, 4, 8, 5, 5, 0, 1, 4, 9, 3, 5, 2, 4, 5, 5, 2, 7, 0, 5,
       2, 0, 1, 8, 9, 5, 0, 6, 2, 4, 0, 4, 9, 0, 1, 7, 5, 2, 9, 5, 3, 3,
       8, 5, 5, 1, 1, 3, 8, 7, 5, 4, 7, 3, 0, 9, 3, 0, 9, 0, 2, 2, 7, 0,
       3, 0, 0, 3, 0, 9, 4, 5, 9, 2, 9, 1, 2, 3, 0, 0, 2, 9, 7, 5, 0, 3,
       8, 7, 2, 3, 8, 5, 6, 2, 2, 5, 3, 5, 6, 3, 6, 3, 3, 9, 4, 7, 7, 3,
       9, 3, 4, 6, 7, 0, 0, 5, 0, 5, 8, 7, 6, 8, 4, 9, 5, 7, 2, 0, 0, 4,
       7, 6, 3, 2, 5, 7, 7, 1, 5, 4, 1, 6, 3, 2, 5, 5, 0, 9, 5, 3, 7, 9,
       8, 9, 1, 0, 4, 3, 0, 1, 7, 0, 6, 1, 1, 6, 0, 8, 2, 7, 6, 8, 8, 0,
       5, 0, 7, 6, 0, 8, 2, 9, 4, 7, 0, 5, 1, 2, 1, 8, 2, 8, 6, 7, 9, 9,
       3, 4, 1, 6, 0, 8, 8, 6, 3, 0, 9, 1, 9, 8, 7, 5, 1, 6, 4, 8, 3, 4,
       6, 1, 3, 5, 9, 0, 9, 0, 5, 2, 3, 4, 4, 7, 3, 1, 6, 7, 1, 7, 7, 4,
       4, 5, 5, 1, 8, 8, 4, 2, 5, 0, 1, 6, 8, 8])

In [14]:
knn_clf.predict(X_test[:300])

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6,
       6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2,
       3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4,
       6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3,
       6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9, 6, 0, 5, 4, 9, 9, 2, 1, 9, 4,
       8, 7, 3, 9, 7, 9, 4, 4, 9, 2, 5, 4, 7, 6, 7, 9, 0, 5, 8, 5, 6, 6,
       5, 7, 8, 1, 0, 1, 6, 4, 6, 7, 3, 1, 7, 1, 8, 2, 0, 2, 9, 9, 5, 5,
       1, 5, 6, 0, 3, 4, 4, 6, 5, 4, 6, 5, 4, 5, 1, 4, 4, 7, 2, 3, 2, 7,
       1, 8, 1, 8, 1, 8, 5, 0, 8, 9, 2, 5, 0, 1, 1, 1, 0, 9, 0, 5, 1, 6,
       4, 2, 3, 6, 1, 1, 1, 3, 9, 5, 2, 9, 4, 5, 9, 3, 9, 0, 3, 6, 5, 5,
       7, 2, 2, 7, 1, 2, 8, 4, 1, 7, 3, 3, 8, 8, 7, 9, 2, 2, 4, 1, 5, 8,
       8, 7, 2, 3, 0, 4, 4, 2, 4, 1, 9, 5, 7, 7, 2, 8, 2, 6, 8, 5, 7, 7,
       9, 1, 8, 1, 5, 0, 3, 0, 1, 9, 9, 4, 1, 8, 2, 1, 2, 9, 7, 5, 9, 2,
       6, 4, 1, 5, 8, 2, 9, 2, 0, 4, 0, 0, 2, 8])

In [15]:
y_test[:300]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6,
       6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 2, 1, 1, 7, 4, 2,
       3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4,
       6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 2, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3,
       6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9, 6, 0, 5, 4, 9, 9, 2, 1, 9, 4,
       8, 7, 3, 9, 7, 4, 4, 4, 9, 2, 5, 4, 7, 6, 7, 9, 0, 5, 8, 5, 6, 6,
       5, 7, 8, 1, 0, 1, 6, 4, 6, 7, 3, 1, 7, 1, 8, 2, 0, 2, 9, 9, 5, 5,
       1, 5, 6, 0, 3, 4, 4, 6, 5, 4, 6, 5, 4, 5, 1, 4, 4, 7, 2, 3, 2, 7,
       1, 8, 1, 8, 1, 8, 5, 0, 8, 9, 2, 5, 0, 1, 1, 1, 0, 9, 0, 3, 1, 6,
       4, 2, 3, 6, 1, 1, 1, 3, 9, 5, 2, 9, 4, 5, 9, 3, 9, 0, 3, 6, 5, 5,
       7, 2, 2, 7, 1, 2, 8, 4, 1, 7, 3, 3, 8, 8, 7, 9, 2, 2, 4, 1, 5, 9,
       8, 7, 2, 3, 0, 4, 4, 2, 4, 1, 9, 5, 7, 7, 2, 8, 2, 6, 8, 5, 7, 7,
       9, 1, 8, 1, 8, 0, 3, 0, 1, 9, 9, 4, 1, 8, 2, 1, 2, 9, 7, 5, 9, 2,
       6, 4, 1, 5, 8, 2, 9, 2, 0, 4, 0, 0, 2, 8])

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

predictions = knn_clf.predict(X_test)
knn_mse = mean_squared_error(y_test, predictions)
knn_rmse = np.sqrt(knn_mse)
knn_rmse