In [3]:
import numpy as np

In [4]:
X = np.random.rand(3,4)

In [5]:
X

array([[0.05624876, 0.87875403, 0.19060514, 0.27397581],
       [0.46989039, 0.42209263, 0.84714122, 0.99583288],
       [0.45372033, 0.96208278, 0.52001136, 0.4584227 ]])

In [6]:
# SVD

U, s, Vt = np.linalg.svd(X)

In [7]:
U

array([[-0.4003034 ,  0.62879772, -0.66661129],
       [-0.67691186, -0.69323381, -0.24742114],
       [-0.61769533,  0.35219357,  0.70314448]])

In [8]:
# every components of s are square root of eigenvalue of X^2

s

array([1.99593957, 0.76392628, 0.1993154 ])

In [9]:
# each column of V is principal component of X

Vt.T

array([[-0.31105745, -0.17092936,  0.82920872,  0.43178619],
       [-0.6171338 ,  0.78383089, -0.06892994, -0.0019154 ],
       [-0.48646183, -0.37211732,  0.14541242, -0.77700632],
       [-0.5345503 , -0.46682008, -0.53527263,  0.45805917]])

In [10]:
# principal component extraction

c1 = Vt.T[:,0]
c2 = Vt.T[:,1]

In [11]:
# 2-dimension projection

W_2 = np.array([c1,c2]).T

In [12]:
X_2_proj = X.dot(W_2)

In [13]:
X_2_proj

array([[-0.79898139,  0.48035511],
       [-1.35107517, -0.52957953],
       [-1.23288256,  0.26904992]])